CREATE TYPE "DutyKind" AS ENUM ('DAY_SLOT', 'TIME_RANGE');

ALTER TABLE "DutyType"
  ADD COLUMN "kind" "DutyKind" NOT NULL DEFAULT 'DAY_SLOT';

ALTER TABLE "DutyRule"
  ALTER COLUMN "byWeekday" SET DEFAULT ARRAY[]::INTEGER[],
  ADD COLUMN "startTime" TEXT,
  ADD COLUMN "endTime" TEXT,
  ADD COLUMN "disabled" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "DutyAssignment"
  ALTER COLUMN "slotIndex" SET DEFAULT 0,
  ADD COLUMN "startsAt" TIMESTAMP(3),
  ADD COLUMN "endsAt" TIMESTAMP(3);
