name: Run Prisma Migrate (one-off)

on:
  workflow_dispatch: {}

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install (workspace)
        run: pnpm -w install

      - name: Prisma migrate deploy (web)
        working-directory: web
        env:
          # 必ず Direct（-pooler なし）を入れること
          DATABASE_URL: ${{ secrets.DIRECT_URL }}
          DIRECT_URL:   ${{ secrets.DIRECT_URL }}
        run: pnpm prisma migrate deploy
